services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ZltjpqOmOkfC44s9NIYvBFX3lJP4WxS7
      POSTGRES_DB: plan_x
    volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: